### ISSUE TITLE
Running  AppRunner.java throws - jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "karate" is not defined

### ISSUE THREAD

**Issue by vidhya03** [vidhya03/http-patch-jax-rs#12]
Running the standalone AppRunner.java throws the below error

`jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "karate" is not defined`
`
------------------------------------------------------------------------
Building HTTP-PATCH-JAX-RS Web APP 1.0-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ HTTP-PATCH-JAX-RS ---
00:02:15.465 [JavaFX Application Thread] ERROR com.intuit.karate.ui.AppSession - javascript function call failed, arg: null
function() {   
  var env = karate.env; // get system property 'karate.env'
  karate.log('karate.env system property was:', env);
  if (!env) {
    env = 'live';
  }
  var config = {
    env: env,
   apiUrl: 'http://http-patch-vidhya.1d35.starter-us-east-1.openshiftapps.com/v1/'
  };
  if (env === 'dev') {
    // customize
   config.apiUrl = 'http://localhost:18080/http-patch-jax-rs/v1';
  } else if (env === 'e2e') {
    // customize
  }
  //Right now commenting the below for future use
//  config.myObject = karate.read('classpath:test.json');
  return config;
}
jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "karate" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1426)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$11$\^eval\_.L:1(<eval>:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at com.intuit.karate.Script.evalFunctionCall(Script.java:1491)
	at com.intuit.karate.Script.call(Script.java:1449)
	at com.intuit.karate.Script.callAndUpdateConfigAndAlsoVarsIfMapReturned(Script.java:1564)
	at com.intuit.karate.ScriptContext.<init>(ScriptContext.java:144)
	at com.intuit.karate.StepDefs.<init>(StepDefs.java:81)
	at com.intuit.karate.cucumber.KarateObjectFactory.getInstance(KarateObjectFactory.java:80)
	at com.intuit.karate.cucumber.KarateObjectFactory.getStepDefs(KarateObjectFactory.java:87)
	at com.intuit.karate.cucumber.KarateBackend.getStepDefs(KarateBackend.java:104)
	at com.intuit.karate.ui.AppSession.getVars(AppSession.java:150)
	at com.intuit.karate.ui.VarsPanel.<init>(VarsPanel.java:62)
	at com.intuit.karate.ui.AppSession.<init>(AppSession.java:104)
	at com.intuit.karate.ui.AppSession.<init>(AppSession.java:69)
	at com.intuit.karate.ui.App.initUi(App.java:63)
	at com.intuit.karate.ui.App.start(App.java:102)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: evaluation of karate-config.js failed:
	at com.intuit.karate.ScriptContext.<init>(ScriptContext.java:153)
	at com.intuit.karate.StepDefs.<init>(StepDefs.java:81)
	at com.intuit.karate.cucumber.KarateObjectFactory.getInstance(KarateObjectFactory.java:80)
	at com.intuit.karate.cucumber.KarateObjectFactory.getStepDefs(KarateObjectFactory.java:87)
	at com.intuit.karate.cucumber.KarateBackend.getStepDefs(KarateBackend.java:104)
	at com.intuit.karate.ui.AppSession.getVars(AppSession.java:150)
	at com.intuit.karate.ui.VarsPanel.<init>(VarsPanel.java:62)
	at com.intuit.karate.ui.AppSession.<init>(AppSession.java:104)
	at com.intuit.karate.ui.AppSession.<init>(AppSession.java:69)
	at com.intuit.karate.ui.App.initUi(App.java:63)
	at com.intuit.karate.ui.App.start(App.java:102)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more
Caused by: com.intuit.karate.exception.KarateException: 
ReferenceError: "karate" is not defined
	at com.intuit.karate.Script.evalFunctionCall(Script.java:1497)
	at com.intuit.karate.Script.call(Script.java:1449)
	at com.intuit.karate.Script.callAndUpdateConfigAndAlsoVarsIfMapReturned(Script.java:1564)
	at com.intuit.karate.ScriptContext.<init>(ScriptContext.java:144)
	... 19 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.729s
Finished at: Wed Jan 24 00:02:15 IST 2018
Final Memory: 8M/153M
`

**Comment by vidhya03** [comment]
Investing in other machine . requesting for help

**Comment by vidhya03** [comment]
This is because of java old version. upgrading to latest java version 1.8.0_161 fixes this issue
